### ISSUE TITLE
[Bug] sitemap不规范

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#436]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/140d8326-1462-423d-ad8d-6519546d5485)

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q @langningchen @boomzero 服务端的this.Username是一个string吧

**Comment by PythonSmall-Q** [comment]
哪一行？

**Comment by langningchen** [comment]
@zhouyiqing0304 Do **NOT** @ me any more if there is nothing important!

**Comment by langningchen** [comment]
@zhouyiqing0304 Do NOT @ me any more if there is nothing important! Especially the most simple and stupid question on the detail of the code! I have said that I am not responsible for the code now, I even do not have the privilege to access backend and databases. I want to spend my precious time on the high-school-entrance-examination instead of these ridiculous questions. This is the last warning!

**Comment by boomzero** [comment]
+1，and use an ide发自我的 iPhone在 2024年2月5日，13:42，Langning Chen ***@***.***> 写道：﻿
@zhouyiqing0304 Do NOT @ me any more if there is nothing important! Especially the most simple and stupid question on the detail of the code! I have said that I am not responsible for the code now, I even do not have the privilege to access backend and databases. I want to spend my precious time on the high-school-entrance-examination instead of these ridiculous questions. This is the last warning!

**Comment by boomzero** [comment]
Well, this is your problem
